'use strict';
const $=id=>document.getElementById(id), STORAGE='parafraseador_v3_';
const get=(k,d)=>{try{return JSON.parse(localStorage.getItem(STORAGE+k))??d}catch{return d}};
const put=(k,v)=>{try{localStorage.setItem(STORAGE+k,JSON.stringify(v));return true}catch{notify('Armazenamento indisponível neste navegador.',true);return false}};
let results={}, explanations=[], lastSource='', selected='corrigido', previous={}, speech=null, busy=false;
const names={corrigido:'✓ Corrigida',formal:'💼 Formal',objetivo:'🎯 Objetiva',simples:'🌿 Simples',cordial:'🤝 Cordial',detalhado:'📝 Detalhado',whatsapp:'💬 WhatsApp',operacional:'🚰 Comunicado operacional'};
const styles=['corrigido','formal','objetivo'];
function notify(msg,error=false,good=false){$('status').textContent=msg;$('status').className='notice'+(error?' error':good?' good':'')}
function clean(t){return t.replace(/\s+/g,' ').trim()}
function baseFix(input){let s=clean(input);if(!s)return '';s=s.replace(/\s+([,.!?;:])/g,'$1').replace(/([,.!?;:])(?=\S)/g,'$1 ').replace(/\b(amanha|reuniao|nao|tambem|voce|sera|ate|informacao|situacao|previsao|horario|manutencao|agua|ja|esta|estao|possivel|atencao)\b/gi,m=>({amanha:'amanhã',reuniao:'reunião',nao:'não',tambem:'também',voce:'você',sera:'será',ate:'até',informacao:'informação',situacao:'situação',previsao:'previsão',horario:'horário',manutencao:'manutenção',agua:'água',ja:'já',esta:'está',estao:'estão',possivel:'possível',atencao:'atenção'})[m.toLowerCase()]||m);s=s.replace(/\b(\d{1,2})\s*(?:horas?|h)\s*(?:da|de)\s*tarde\b/gi,(_,h)=>String((Number(h)%12)+12)+'h').replace(/\b(\d{1,2})\s*(?:horas?|h)\s*(?:da|de)\s*manh[aã]\b/gi,(_,h)=>Number(h)+'h');s=s.replace(/\b(\d{1,2}):\s*(\d{2})\b/g,(_,h,m)=>Number(h)+'h'+(m==='00'?'':m));s=s[0].toUpperCase()+s.slice(1);if(!/[.!?]$/.test(s))s+='.';return s}
function fallback(t){const c=baseFix(t);return {corrigido:c,formal:c,objetivo:c}}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function wordDiff(original,changed){let a=new Set(original.toLowerCase().match(/[\p{L}\p{N}]+/gu)||[]);return changed.split(/(\s+)/).map(w=>{let k=w.toLowerCase().replace(/[^\p{L}\p{N}]/gu,'');return k&&!a.has(k)?'<mark>'+escapeHtml(w)+'</mark>':escapeHtml(w)}).join('')}
function render(){const box=$('resultCards');box.innerHTML='';for(const [key,value] of Object.entries(results)){const card=document.createElement('article');card.className='result';card.innerHTML='<div class="resultHead"><strong>'+escapeHtml(names[key]||key)+'</strong><span class="muted">Editável</span></div><textarea aria-label="Texto '+escapeHtml(key)+'"></textarea><div class="diff" hidden></div><div class="resultActions"><button data-act="copy">📋 Copiar</button><button data-act="share">↗ Compartilhar</button><button data-act="diff">Comparar</button><button data-act="undo">↶ Desfazer</button><button data-act="select">Usar esta versão</button></div>';const ta=card.querySelector('textarea');ta.value=value;ta.addEventListener('input',()=>{results[key]=ta.value});card.querySelectorAll('button').forEach(b=>b.addEventListener('click',async()=>{const act=b.dataset.act;if(act==='copy'){await copyText(ta.value)}else if(act==='share'){if(navigator.share){try{await navigator.share({text:ta.value})}catch(e){if(e.name!=='AbortError')notify('Não foi possível compartilhar.',true)}}else window.open('https://wa.me/?text='+encodeURIComponent(ta.value),'_blank','noopener')}else if(act==='diff'){let el=card.querySelector('.diff');el.hidden=!el.hidden;if(!el.hidden)el.innerHTML='<strong>Palavras novas destacadas:</strong><p>'+wordDiff(lastSource,ta.value)+'</p>'}else if(act==='undo'){ta.value=previous[key]??value;results[key]=ta.value}else{selected=key;notify('Versão selecionada: '+(names[key]||key),false,true)}}));box.appendChild(card)}if(!Object.keys(results).length)box.innerHTML='<div class="empty">Suas três versões aparecerão aqui.</div>'}
async function copyText(text){try{await navigator.clipboard.writeText(text);notify('Texto copiado!',false,true)}catch{notify('Não foi possível copiar automaticamente. Selecione e copie o texto.',true)}}
function detectWarnings(input,outputs){const out=[];if(/\b(?:amanh[aã]|hoje|ontem)\b/i.test(input)&&/\b(?:\d{1,2})(?:h|:\d{2})?\b/.test(input)===false)out.push('Confira se há um horário que precisa ser informado.');if(/\b(?:às|as)\s*\d{1,2}(?!\s*(?:h|:|horas|da tarde|da manhã|da noite))\b/i.test(input))out.push('Horário ambíguo: confirme se é manhã ou tarde.');const originalNumbers=(input.match(/\d+(?:[.,:]\d+)*/g)||[]).sort().join('|');for(const v of Object.values(outputs)){const numbers=(v.match(/\d+(?:[.,:]\d+)*/g)||[]).sort().join('|');if(numbers!==originalNumbers){out.push('Confira os números e horários: a reescrita pode ter alterado a forma de apresentação.');break}}return [...new Set(out)]}
function showWarnings(w){$('warnings').hidden=!w.length;$('warnings').textContent=w.join('\n')}
async function askAI(payload){const url=get('worker','');if(!url)throw Error('IA não configurada');const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),25000);try{const res=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),signal:controller.signal});const body=await res.json().catch(()=>({}));if(!res.ok)throw Error(body.error||'Erro no serviço de IA ('+res.status+')');if(!body.versions||typeof body.versions!=='object')throw Error('Resposta da IA inválida');return body}finally{clearTimeout(timer)}}
async function generate(keys=styles,instruction=''){const source=$('source').value.trim();if(!source){notify('Digite ou fale um texto antes de gerar.',true);$('source').focus();return}if(source.length>5000){notify('Limite de 5.000 caracteres por solicitação.',true);return}if(busy)return;busy=true;$('generate').disabled=true;$('generate').textContent='⏳ Gerando...';lastSource=source;let requested=keys;try{let output,ai=false;if($('privacy').checked&&get('worker','')){const data=await askAI({text:source,styles:requested,length:$('length').value,tone:$('tone').value,recipient:$('recipient').value,dictionary:get('dictionary',[]),instruction,reference:instruction?(results[selected]||''):''});output=data.versions;explanations=Array.isArray(data.explanations)?data.explanations:[];ai=true}else{if(instruction||requested.some(k=>!styles.includes(k)))throw Error('Estilo avançado exige IA configurada e consentimento.');output=fallback(source);explanations=['Modo básico: apenas ajustes limitados de espaçamento, pontuação, acentos frequentes e horários.'];}previous={...results};if(requested.length===3)results={};for(const k of requested){if(typeof output[k]!=='string'||!output[k].trim())throw Error('A IA não devolveu o estilo '+k);results[k]=output[k].trim()}render();showWarnings(detectWarnings(source,results));$('mode').textContent=ai?'✨ Gerado com IA':'⚙ Modo básico';notify(ai?'Três versões geradas com IA. Confira nomes, horários e fatos.':'Modo básico aplicado. Para paráfrases completas, configure a IA.',false,true)}catch(e){const msg=e.name==='AbortError'?'Tempo de resposta esgotado.':e.message;notify('Não foi possível gerar com IA: '+msg,true);if(requested.length===3){previous={...results};results=fallback(source);explanations=['Modo de reserva: revisão simples, sem reescrita inteligente.'];render();showWarnings(detectWarnings(source,results));$('mode').textContent='⚙ Reserva básica';notify('IA indisponível: modo básico exibido. '+msg,true)}}finally{busy=false;$('generate').disabled=false;$('generate').textContent='✦ Gerar 3 versões'}}
function showHistory(){const h=get('history',[]);$('history').innerHTML='';if(!h.length){$('history').textContent='Nenhum texto salvo.';return}for(const entry of h){const item=document.createElement('div');item.className='historyItem';const p=document.createElement('div');p.className='preview';p.textContent=(entry.favorite?'★ ':'')+new Date(entry.date).toLocaleString('pt-BR')+' — '+entry.source;item.appendChild(p);const group=document.createElement('div');group.className='tools';[['Abrir',()=>{ $('source').value=entry.source;lastSource=entry.source;results={...entry.results};previous={...results};render();$('count').textContent=entry.source.length+' caracteres';window.scrollTo({top:0,behavior:'smooth'})}],[(entry.favorite?'★':'☆'),()=>{entry.favorite=!entry.favorite;put('history',h);showHistory()}],['Excluir',()=>{put('history',h.filter(x=>x.id!==entry.id));showHistory()}]].forEach(([t,fn])=>{const b=document.createElement('button');b.textContent=t;b.addEventListener('click',fn);group.appendChild(b)});item.appendChild(group);$('history').appendChild(item)}}
$('source').addEventListener('input',()=>{$('count').textContent=$('source').value.length+' caracteres'});
$('generate').addEventListener('click',()=>generate());$('clearBtn').addEventListener('click',()=>{$('source').value='';$('count').textContent='0 caracteres';$('source').focus()});
$('styles').addEventListener('click',e=>{const k=e.target.closest('button')?.dataset.style;if(k)generate([k])});$('reviseBtn').addEventListener('click',()=>{const instruction=$('instruction').value.trim();if(!instruction)return notify('Escreva uma instrução para revisar.',true);generate([selected],instruction)});
$('explainBtn').addEventListener('click',()=>{const e=$('explanations');e.hidden=!e.hidden;e.textContent=explanations.length?explanations.join('\n'):'Nenhuma explicação disponível para esta geração.'});
$('saveBtn').addEventListener('click',()=>{if(!lastSource||!Object.keys(results).length)return notify('Gere um texto antes de salvar.',true);let h=get('history',[]);h.unshift({id:Date.now()+Math.random(),date:Date.now(),source:lastSource,results:{...results},favorite:false});put('history',h.slice(0,100));showHistory();notify('Texto salvo neste navegador.',false,true)});
$('deleteAll').addEventListener('click',()=>{if(confirm('Apagar todo o histórico salvo neste navegador?')){put('history',[]);showHistory()}});
$('exportBtn').addEventListener('click',()=>{const data={version:3,history:get('history',[]),dictionary:get('dictionary',[])};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='parafraseador-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
$('importFile').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const data=JSON.parse(await file.text());if(!Array.isArray(data.history)||data.history.length>1000)throw Error('Backup inválido');const valid=data.history.filter(x=>typeof x.source==='string'&&x.source.length<=5000&&x.results&&typeof x.results==='object').slice(0,100);if(!confirm('Importar '+valid.length+' registros? Isso substituirá seu histórico.'))return;put('history',valid);if(Array.isArray(data.dictionary))put('dictionary',data.dictionary.filter(x=>typeof x==='string').slice(0,100));showHistory();notify('Backup importado.',false,true)}catch{notify('Não foi possível importar o arquivo.',true)}finally{e.target.value=''}});
$('settingsBtn').addEventListener('click',()=>{$('workerUrl').value=get('worker','');$('settingsDialog').showModal()});$('saveSettings').addEventListener('click',e=>{const url=$('workerUrl').value.trim();if(url&&!/^https:\/\/[\w.-]+(?:\/[^\s]*)?$/.test(url)){e.preventDefault();notify('Informe uma URL HTTPS válida.',true);return}put('worker',url);notify(url?'Servidor de IA configurado. Marque o consentimento para usar.':'Servidor removido. Modo básico disponível.',false,true)});
$('dictBtn').addEventListener('click',()=>{$('dictionary').value=get('dictionary',[]).join('\n');$('dictDialog').showModal()});$('saveDict').addEventListener('click',()=>{put('dictionary',$('dictionary').value.split('\n').map(x=>x.trim()).filter(Boolean).slice(0,100));notify('Dicionário salvo.',false,true)});
$('micBtn').addEventListener('click',()=>{const Rec=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Rec)return notify('Reconhecimento de voz indisponível. Use o microfone do teclado do celular.',true);if(speech){speech.stop();return}speech=new Rec();speech.lang='pt-BR';speech.continuous=true;speech.interimResults=true;let committed=$('source').value.trim();let finalized='';speech.onresult=e=>{let partial='';for(let i=e.resultIndex;i<e.results.length;i++){const t=e.results[i][0].transcript;if(e.results[i].isFinal)finalized+=' '+t;else partial+=' '+t} $('source').value=[committed,finalized.trim(),partial.trim()].filter(Boolean).join(' ').trim();$('count').textContent=$('source').value.length+' caracteres'};speech.onerror=e=>{if(e.error!=='aborted')notify('Microfone: '+e.error+'. Você pode usar o teclado de voz.',true)};speech.onend=()=>{speech=null;$('micBtn').textContent='🎙️ Falar';notify('Ditado finalizado. Confira a transcrição antes de gerar.')};try{speech.start();$('micBtn').textContent='⏹ Parar';notify('Ouvindo... toque em Parar quando terminar.')}catch{speech=null;notify('Não foi possível iniciar o microfone.',true)}});
showHistory();
